In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
file_path = "../Dataset/XAUUSD_M1.csv"
df = pd.read_csv(file_path)
df.shape

FileNotFoundError: [Errno 2] No such file or directory: '../Dataset/XAUUSD_M1.csv'

In [ ]:
import pandas as pd
df_XAUUSD_M1 = pd.read_csv('..\..\Dataset\XAUUSD_M1.csv')
df_XAUUSD_M1

           id      open      high       low     close
0           1  3358.289  3358.289  3357.345  3357.635
1           2  3357.625  3357.815  3357.298  3357.805
2           3  3357.815  3358.185  3357.265  3358.005
3           4  3358.005  3358.475  3357.955  3358.085
4           5  3358.095  3358.915  3358.085  3358.775
...       ...       ...       ...       ...       ...
99995   99996  4066.915  4069.735  4066.595  4067.415
99996   99997  4067.465  4068.115  4064.375  4066.355
99997   99998  4066.355  4071.325  4066.318  4071.018
99998   99999  4071.018  4072.485  4070.595  4070.935
99999  100000  4070.915  4071.305  4069.095  4069.125

[100000 rows x 5 columns]

In [73]:
diabetes_map = {True: 1, False: 0}
df['diabetes'] = df['diabetes'].map(diabetes_map)
df

,num_preg,glucose_conc,diastolic_bp,thickness,insulin,bmi,diab_pred,age,skin,diabetes
0,6,148,72,35,0,33.6,0.627,50,1.3790,1
1,1,85,66,29,0,26.6,0.351,31,1.1426,0
2,8,183,64,0,0,23.3,0.672,32,0.0000,1
3,1,89,66,23,94,28.1,0.167,21,0.9062,0
4,0,137,40,35,168,43.1,2.288,33,1.3790,1
...,...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,1.8912,0
764,2,122,70,27,0,36.8,0.340,27,1.0638,0
765,5,121,72,23,112,26.2,0.245,30,0.9062,0
766,1,126,60,0,0,30.1,0.349,47,0.0000,1
767,1,93,70,31,0,30.4,0.315,23,1.2214,0

In [74]:
df.shape

(768, 10)

In [75]:
x = df.drop('diabetes', axis=1)
y = df['diabetes']

In [76]:
x = np.array(x)
y = np.array(y)
type(x)

numpy.ndarray

In [77]:
x

array([[  6.    , 148.    ,  72.    , ...,   0.627 ,  50.    ,   1.379 ],
       [  1.    ,  85.    ,  66.    , ...,   0.351 ,  31.    ,   1.1426],
       [  8.    , 183.    ,  64.    , ...,   0.672 ,  32.    ,   0.    ],
       ...,
       [  5.    , 121.    ,  72.    , ...,   0.245 ,  30.    ,   0.9062],
       [  1.    , 126.    ,  60.    , ...,   0.349 ,  47.    ,   0.    ],
       [  1.    ,  93.    ,  70.    , ...,   0.315 ,  23.    ,   1.2214]],
      shape=(768, 9))

In [78]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x = scaler.fit_transform(x)
x

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.46849198,
         1.4259954 ,  0.90726993],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.36506078,
        -0.19067191,  0.53090156],
       [ 1.23388019,  1.94372388, -0.26394125, ...,  0.60439732,
        -0.10558415, -1.28821221],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.68519336,
        -0.27575966,  0.15453319],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.37110101,
         1.17073215, -1.28821221],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.47378505,
        -0.87137393,  0.65635768]], shape=(768, 9))

In [79]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((614, 9), (154, 9), (614,), (154,))